### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getRetryCount()I in class Lcom/tencent/qcloud/core/http/HttpTaskMetrics

### ISSUE THREAD

**Issue by hayukleung** [tencentyun/qcloud-sdk-android#10]
[COSXML-5.9.6](https://github.com/tencentyun/qcloud-sdk-android/releases/tag/cosxml-5.9.6) [Latest](https://github.com/tencentyun/qcloud-sdk-android/releases/latest)
语音识别增加极速语音识别。
优化路径上传大文件长度获取耗时。
灯塔增加重试次数。
qcloud-foundation-1.5.48.aar 缺失灯塔重试次数 getRetryCount，需要更换为 qcloud-foundation-1.5.49.aar

**Comment by jordanqin** [comment]
已修复
