### ISSUE TITLE
进度回调异常

### ISSUE THREAD

**Issue by may7be** [tencentyun/qcloud-sdk-android#11]
视频上传过程中，进度回调多次出现回退情况，why？
![image](https://user-images.githubusercontent.com/24719809/216252272-a9162ab5-d207-4fd5-983d-0358b07fc7b3.png)

![image](https://user-images.githubusercontent.com/24719809/216252219-76645f3c-b560-47a5-b77b-2512f3f83756.png)

![image](https://user-images.githubusercontent.com/24719809/216252404-9e684512-196c-466b-8c4b-83218b797b55.png)

![image](https://user-images.githubusercontent.com/24719809/216252511-3783b016-ae7a-416c-a7d6-f1b353422dcd.png)

**Comment by jordanqin** [comment]
这种情况是可能的，建议在业务层做处理，比如：进度回退后进度条不做变化等
出现这种情况的原因是：分块上传时是多个http上传请求，其中某一个请求进行到一部分后失败，然后重试，此时进度就可能回退
