### ISSUE TITLE
Android 14专属目录下图片无法上传。

### ISSUE THREAD

**Issue by hezhipengzipp** [tencentyun/qcloud-sdk-android#15]
/storage/emulated/0/Android/data/com.het.family.sport.controller/files/1718197808621_091225.jpg，
像这个目录下无法上传。

Failed: CosXmlClientException{errorCode=20002message=com.tencent.qcloud.core.common.QCloudClientException: javax.net.ssl.SSLHandshakeException: Unacceptable certificate: C=NZ, ST=Auckland, L=Auckland, O=XK72 Ltd, OU=https://charlesproxy.com/ssl, CN="Charles Proxy CA (21 Feb 2022, NS800797)"}

**Comment by jordanqin** [comment]
@hezhipengzipp 看报错是Charles代理的问题，请检查代理的证书是否安装正确，而且cos sdk不提供上传文件权限的相关操作，需要业务层处理权限相关，cos sdk会根据传入的路径直接取读取，没权限的话就抛出异常
