### ISSUE TITLE
上传图片有极小的概率出现上传的图片是0kb的问题

### ISSUE THREAD

**Issue by minorlai** [tencentyun/qcloud-sdk-android#16]

**Comment by minorlai** [comment]
版本号：5.9.31

**Comment by jordanqin** [comment]
@minorlai 请检查上传时刻本地图片是否为0kb，也可以用上传完crc64校验作为兜底策略https://cloud.tencent.com/document/product/436/40334#be092737-822e-4f89-8975-77dafb01ed50

**Comment by minorlai** [comment]
> @minorlai 请检查上传时刻本地图片是否为0kb，也可以用上传完crc64校验作为兜底策略https://cloud.tencent.com/document/product/436/40334#be092737-822e-4f89-8975-77dafb01ed50

上传时有校验本地图片大小不为0kb，再执行上传的操作，问题是上传成功后，返回的图片的实际文件大小为0kb，
在onSuccess回调之后能否验证当前图片是否大于0kb？
