### ISSUE TITLE
新版捕获到 java.lang.IllegalStateException  好多这样的错误，

### ISSUE THREAD

**Issue by wangfens** [tencentyun/qcloud-sdk-android#17]
Null interceptor: [com.tencent.qcloud.core.http.HttpLoggingInterceptor@4e2d656, com.tencent.qcloud.core.http.HttpLoggingInterceptor@e67a6d7, com.tencent.qcloud.core.http.interceptor.RetryInterceptor@841bbc4, com.tencent.qcloud.core.http.HttpLoggingInterceptor@8cadaad, com.tencent.qcloud.core.http.interceptor.RetryInterceptor@bce01e2, com.tencent.qcloud.core.http.HttpLoggingInterceptor@215d973, com.tencent.qcloud.core.http.interceptor.RetryInterceptor@d80d030, com.tencent.qcloud.core.http.HttpLoggingIntercep
com.tencent.qcloud.core.http.OkHttpClientImpl.init(OkHttpClientImpl.java:112)
Null interceptor: [null, null, com.tencent.qcloud.core.http.interceptor.TrafficControlInterceptor@6fc85c0, com.tencent.qcloud.core.http.interceptor.RedirectInterceptor@cc5a2f9, com.tencent.qcloud.core.http.HttpLoggingInterceptor@d64723e, com.tencent.qcloud.core.http.interceptor.RetryInterceptor@887b89f]
com.tencent.qcloud.core.http.OkHttpClientImpl.init(OkHttpClientImpl.java:112)
帮忙确认下，感谢

**Comment by jordanqin** [comment]
@wangfens 麻烦发一下用的cos sdk哪个版本？是怎么依赖的？（Maven还是离线aar）
可以的话再发一下完整的报错堆栈
