### ISSUE TITLE
请问kotlin版本如何实现断点续传、暂停、取消等操作

### ISSUE THREAD

**Issue by bjshtech** [tencentyun/qcloud-sdk-android#2]
请问kotlin版本如何实现断点续传、暂停、取消等操作

**Comment by jordanqin** [comment]
请参考我们的示例demo，其中有上传下载的断点续传、暂停、取消。demo是用Java写的，kotlin同理
https://github.com/tencentyun/qcloud-sdk-android-samples/tree/master/COSTransferPractice
