### ISSUE TITLE
多线程疑问

### ISSUE THREAD

**Issue by fqhznh** [tencentyun/qcloud-sdk-android#2]
您好， 我看了你们的源码， 使用线程池的方式， 支持多线程上传和下载，但是里面有太多全局锁， 导致多线程时被阻塞， 请问有什么更好的处理方式？

**Comment by konakonall** [comment]
@fqhznh 目前我们用的是 jdk 中的标准线程池 ThreadPoolExecutor。可否具体描述一下问题，是什么地方用到了大量全局锁，在什么场景下出现了上传下载大量阻塞的情况呢？

**Comment by fqhznh** [comment]
这块， 我已经更改完成了。它原来用了很多的共享变量， 是线程非安全的， 所以用了全局锁，来保证线程安全， 但是这样就导致多线程下载失效了。

**Comment by konakonall** [comment]
如果是一些互斥资源，是需要加锁或者无锁算法来实现线程安全，这个没有疑问。因为不了解你的业务场景，暂时无法给出详细的建议。

**Comment by fqhznh** [comment]
您好！

	您测试过可以多线程上传么？我在跟踪测试的时候， 没有只能一个线程上传， 但是看了代码， 使用了线程池， 支持2个线程上传， 所以才跟踪了代码，例如下面这些代码（只是例举了部分），都用了synchronized，因为全局锁，导致不能多线程并发。其实这些是可以不用synchronized，采用其他的方式，避免使用共享变量，是可以避免的。
	

	Task.java
	


	RetryAndTrafficControlInterceptor.java
	


	UploadService.java

**Comment by konakonall** [comment]
@fqhznh 你好，我们测试过多线程上传。对于 RetryAndTrafficControlInterceptor，有一些记录状态的变量访问加了锁，但是这些访问只是修改一些状态，不是一个耗时操作，并不会阻塞其他线程的网络IO操作，所以是可以并发的。而 Task 标识一个任务，在它上面加锁不会影响到其他任务。
