### ISSUE TITLE
请更新 jcenter 版本

### ISSUE THREAD

**Issue by JiongBull** [tencentyun/qcloud-sdk-android#4]
![image](https://user-images.githubusercontent.com/4413502/49914689-3bcf6b00-fecd-11e8-8bad-eeab5d76c600.png)

https://jcenter.bintray.com/com/tencent/qcloud/cosxml/

![image](https://user-images.githubusercontent.com/4413502/49914636-0dea2680-fecd-11e8-981a-5b356f8b8ab0.png)

**Comment by bradyxiao** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/4413502/49914689-3bcf6b00-fecd-11e8-8bad-eeab5d76c600.png)
> 
> https://jcenter.bintray.com/com/tencent/qcloud/cosxml/
> 
> ![image](https://user-images.githubusercontent.com/4413502/49914636-0dea2680-fecd-11e8-981a-5b356f8b8ab0.png)

请使用这个 repository ：
https://dl.bintray.com/tencentqcloudterminal/maven/com/tencent/qcloud/cosxml/
