### ISSUE TITLE
NPE问题

### ISSUE THREAD

**Issue by hewjinxu** [tencentyun/qcloud-sdk-android#5]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
   * com.tencent.qcloud:cosxml:5.4.19
* 您使用的SDK版本号是多少？
   * 2.6.5

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
   用户 ID

unknown
发生时间

2019-03-16 18:28:48
上报时间

2019-03-16 18:28:50
应用包名

com.blackshark.discovery
应用版本

d25df14
使用时长

7 分 32 秒
前后台状态

后台
设备机型

SKR-A0
系统版本

Android 8.1.0,level 27
ROM

blackshark/SKR-A0
CPU架构

arm64-v8a

* 使用更高版本的SDK是否解决了您的问题？
   * 概率问题，需要你们的研发check code

* 这个问题是否和特定的网络环境有关系？
   * Bugly上报

* 您集成我们SDK的方式是什么？
   * gradle集成：api 'com.tencent.qcloud:cosxml:5.4.19'

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。
   * Bugly日志上报

# main(2)
java.lang.NullPointerException
Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
解析原始
1 com.tencent.qcloud.logutils.LogServer.onActivityStarted(LogServer.java:58)
2 android.app.Application.dispatchActivityStarted(Application.java:211)
3 android.app.Activity.onStart(Activity.java:1252)
4 android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:614)
5 android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
6 android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1337)
7 android.app.Activity.performStart(Activity.java:7080)
8 android.app.Activity.performRestart(Activity.java:7155)
9 android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:4161)
10 android.app.ActivityThread.-wrap29(Unknown Source)
11 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
12 android.os.Handler.dispatchMessage(Handler.java:106)
13 android.os.Looper.loop(Looper.java:164)
14 android.app.ActivityThread.main(ActivityThread.java:6530)
15 java.lang.reflect.Method.invoke(Native Method)
16 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:444)
17 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:812)

**Comment by hewjinxu** [comment]
今天发现了另一个NPE问题，建议coder 做下保护
# main(2)
java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.ClipData$Item android.content.ClipData.getItemAt(int)' on a null object reference
解析原始
1 com.tencent.qcloud.logutils.LogServer.onActivityStarted(LogServer.java:57)
2 android.app.Application.dispatchActivityStarted(Application.java:230)
3 android.app.Activity.onStart(Activity.java:1284)
4 android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:614)
5 android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
6 android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1394)
7 android.app.Activity.performStart(Activity.java:7201)
8 android.app.ActivityThread.handleStartActivity(ActivityThread.java:2980)
9 android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
10 android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
11 android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
12 android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
13 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
14 android.os.Handler.dispatchMessage(Handler.java:106)
15 android.os.Looper.loop(Looper.java:193)
16 android.app.ActivityThread.main(ActivityThread.java:6758)
17 java.lang.reflect.Method.invoke(Native Method)
18 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
19 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by bradyxiao** [comment]
多谢，已fix 这个bug
方法 1 : 使用 compile 'com.tencent.qcloud:cosxml:5.4.20' 及以上版本；
方法 2：指定 com.tencent.qcloud:logUtils:5.4.22;
如  compile ('com.tencent.qcloud:cosxml:5.4.19'){
     exclude group:'com.tencent.qcloud', module: 'logUtils' }
   compile 'com.tencent.qcloud:logUtils:5.4.22'
