### ISSUE TITLE
QCloudClientException: java.net.SocketTimeoutException异常

### ISSUE THREAD

**Issue by kylin17** [tencentyun/qcloud-sdk-android#6]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？**对象（图片）存储及下载服务**

* 您使用的SDK版本号是多少？**5.4.23、5.4.25**

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]**真机，Android5.1工控机，以太网**

* 使用更高版本的SDK是否解决了您的问题？**否**

* 这个问题是否和特定的网络环境有关系？**否**

* 您集成我们SDK的方式是什么？**gradle**

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

网络是正常的，ping `carimage-1255419856.cos.ap-chengdu.myqcloud.com` 及其他域名均连接正常。
目前已知的现象是Android端图片上传频率较高，使用线程池做多线程上传，约1分钟2、3张。
异常名称：**com.tencent.qcloud.core.common.QCloudClientException: java.net.SocketTimeoutException**

<img width="717" alt="WechatIMG1639" src="https://user-images.githubusercontent.com/1879771/59168685-59724a00-8b69-11e9-8592-2b2ecd00a509.png">

**Comment by kylin17** [comment]
补充现象：这个异常报出来之后，后续线程池队列中的图片就再也上传不成功了。

**Comment by bradyxiao** [comment]
read ->导致的socketTimeoutException的主要原因是：读取response时超时了；
1）设置 socket read write time 较长看看；
2）可以抓下包分析下哈
