### ISSUE TITLE
cos-ktx 为什么不更新了？

### ISSUE THREAD

**Issue by CoenQian** [tencentyun/qcloud-sdk-android#7]
![image](https://user-images.githubusercontent.com/4413502/182277015-44b8a37b-fa4c-4e4a-ba3a-dcac94c87c16.png)

只有 21 年的一个版本，是不维护了么？需要明确一下，我们好切换成非协程版本的 SDK。

**Comment by jordanqin** [comment]
暂时没有新功能的规划了，目前的计划是仅维护旧版本。
