### ISSUE TITLE
TransferManager设计问题

### ISSUE THREAD

**Issue by addhaloka** [tencentyun/qcloud-sdk-android#8]
一、TransferManager似乎没办法进行同步访问?
二、设置回调的顺序问题:
final COSXMLUploadTask uploadTask = transferManager.upload(...); // 任务返回前已经启动了
uploadTask.setXXXListener(...); // 如果任务足够快, 在设置回调前已经完成了, 会怎样?

**Comment by rickenwang** [comment]
uploadTask 会保存任务执行的结果，并在设置监听时会检查任务是否结束，如果结束了，会直接根据任务的结果来调用监听器对应的方法。
